// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuipnjhlingjuisaxovi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1aXBuamhsaW5nanVpc2F4b3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mzk2NTAsImV4cCI6MjA1NjMxNTY1MH0.0eKmDPdkTIEei30YlF9PduUUrPx9Valxv0XCCXA3zBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);